### PR TITLE
Remove iotesters for everything besides the cordic

### PR DESCRIPTION
**Pull request by ekiwi**
Ready to merge. Now also includes some formal tests.

### CODE REVIEW

**Comment by ekiwi** [comment]
I added a formal check for the fifos and they all seems to pass. Maybe there is something wrong with how I rewrote the test.

**Comment by ekiwi** [comment]
I fixed the UART test which had a rather obvious bug.

**Comment by ekiwi** [comment]
For the fifo test I removed one assertion that kept on failing and that might be erroneous.

**Comment by schoeberl** [comment]
BIG thanks @ekiwi for updating all the tests, also of my code. Also nice that there are formal tests for the FIFO now.

**Pull request merged**
