### PR TITLE
Port to latest chisel-3.5 and add CI testing

### PR DESCRIPTION
**Pull request by ekiwi**

### CODE REVIEW

**Comment by ekiwi** [comment]
This subsumes https://github.com/freechipsproject/ip-contributions/pull/15

**Comment by ekiwi** [comment]
Tests on this PR currently fail due to: https://github.com/chipsalliance/chisel3/pull/2080

**Comment by ekiwi** [comment]
With the latest `chisel3` snapshot, all tests pass.

@schoeberl This PR is ready for review now.

**Review by schoeberl — COMMENTED** [review]
I assume the dependency on snapshot versions is just temporarily until Chisel 3.5 is out.

**Comment by ekiwi** [comment]
> I assume the dependency on snapshot versions is just temporarily until Chisel 3.5 is out.

They way this is normally handled by other libraries in the chisel ecosystem is that all development happens against the latest snapshot versions and then releases to maven happen from a stable branch that tracks a release version of chisel.

So in this case you could make a `v0.4` branch that will always target the `X.4` release and then we can merge this PR and the main branch will be the development against the latest Chisel.

If you only want to depend on stable versions, we could delay merging this PR until the `X.5` release.

**Comment by schoeberl** [comment]
I am fine with this approach. We (me, you?) should just be aware of to publish a new version of this library (and others) when Chisel 3.5 is out. Looks like Chisel/Scala/Java library version handling is not that trivial. Maybe it cannot be ;-)

**Pull request merged**
